#esercizio A
numero = input("inserire un numero:")
print(numero)
numero = input("inserire un numero:")
print(numero)
numero = input("inserire un numero:")
print(numero)
numero = input("inserire un numero:")
print(numero)
numero = input("inserire un numero:")
print(numero)
#esercizio B
lista = []
numero = input("inserire un numero:")
lista.append(numero)
numero = input("inserire un numero:")
lista.append(numero)
numero = input("inserire un numero:")
lista.append(numero)
numero = input("inserire un numero:")
lista.append(numero)
numero = input("inserire un numero:")
lista.append(numero)
print(lista.reverse())
